const C=[
['eye-drop','Eye Drop',15,'Enclomisign Enclomiphene Tablets, Brimonidine Timolol Eye Drops, Bimatoprost Ophthalmic Solution 0.01 and more',[['Enclomisign Enclomiphene Tablets','Enclomisign','50 mg','Tablet'],['Brimonidine Timolol Eye Drops','—','Eye drops','Drop'],['Bimatoprost Ophthalmic Solution 0.01','—','0.01','Ophthalmic solution']]],
['blood-pressure','Blood Pressure Medicine',13,'Telmisartan 40 Mg Tablet, Telmisartan 80 Mg Tablet, Telmisartan 20 Mg Tablet and more',[['Telmisartan 20 Mg Tablet','—','20 mg','Tablet'],['Telmisartan 40 Mg Tablet','—','40 mg','Tablet'],['Telmisartan 80 Mg Tablet','—','80 mg','Tablet']]],
['antidepressant','Antidepressant & Anti Anxiety Medicines',9,'7.5 mg Zop Zopiclone Tablets, 200mg Modvigil Modafinil Tablets, 400mg Modasmart Modafinil Tablets and more',[['Zop 7.5 mg Zopiclone Tablets','Zop','7.5 mg','Tablet'],['Modvigil Modafinil Tablets','Modvigil','200 mg','Tablet'],['Modasmart Modafinil Tablets','Modasmart','400 mg','Tablet']]],
['malaria','Malaria Medicine',20,'Arteheal L, Ridsunate, Lariago DS and more',[['Arteheal L','Arteheal','80 mg + 480 mg','Tablet'],['Ridsunate','—','200 mg','Tablet'],['Lariago DS','Lariago','500 mg','Tablet']]],
['cardiac','Cardiac Drugs',10,'Acetazolamide Tablets, Amiodarone 200mg Tablet, Amiodarone 100 Mg Tablets and more',[['Acetazolamide Tablets','—','250 mg','Tablet'],['Amiodarone Tablet','—','200 mg','Tablet'],['Amiodarone Tablets','—','100 mg','Tablet']]],
['praziquantel','Praziquantel Tablets',9,'Biltree Praziquantel, Praziquna Plus, PraziJol and more',[['Biltree Praziquantel Tablet','Biltree','600 mg','Tablet'],['Praziquna Plus Praziquantel Tablet','Praziquna Plus','600 mg','Tablet'],['PraziJol Praziquantel Tablet','PraziJol','600 mg','Tablet']]],
['diabetes','Diabetes Medicine',8,'Vildagliptin, Metformin, Dapagliflozin and more',[['Vildagliptin Prolonged Release Tablets IP','—','—','Tablet'],['Metformin Hydrochloride Sustained Release Tablet','—','—','Tablet'],['Vildagliptin And Dapagliflozin Tablets','—','—','Tablet']]],
['vitamins','Vitamin Tablets & Capsules',8,'Cholecalciferol Capsules USP 60000IU, Itraconazole 200 Mg Capsule, Vitamin C Tablets and more',[['Cholecalciferol Capsules USP','—','60000 IU','Capsule'],['Itraconazole 200 Mg Capsule','—','200 mg','Capsule'],['Vitamin C Tablets','—','—','Tablet']]],
['antihistamines','Antihistamines',6,'Levocetirizine, Loratadine, Bepotastine and more',[['Levocetirizine Dihydrochloride Tablets I.P.','—','—','Tablet'],['Loratadine Tablet IP','—','—','Tablet'],['Bepotastine Besilate 10 Mg Tablet','—','10 mg','Tablet']]],
['fenbendazole','Fenbendazole Tablet',6,'444mg, 222mg and 500mg Wormichrist Fenbendazole Tablets and more',[['Wormichrist Fenbendazole Tablets','Wormichrist','444 mg','Tablet'],['Wormichrist Fenbendazole Tablets','Wormichrist','222 mg','Tablet'],['Wormichrist Fenbendazole Tablets','Wormichrist','500 mg','Tablet']]],
['fertility','Fertility Enhancer Drugs',7,'Test-C Testosterone Cypionate Injection, Natural Micronized Progesterone, Dydrogesterone and more',[['Test-C Testosterone Cypionate Injection','Test-C','250 mg','Injection'],['Natural Micronized Progesterone 200mg Tablet','—','200 mg','Tablet'],['Dydrogesterone Tablet IP','—','10 mg','Tablet']]],
['anti-infective-agent','Anti Infective Agent',8,'Itraconazole Cream 1%, Banocide Forte, Eofil Diethylcarbamazine and more',[['Itraconazole Cream 1%','—','1%','Cream'],['Banocide Forte','Banocide','—','Tablet'],['Eofil Diethylcarbamazine Tablets','Eofil','150 mg','Tablet']]],
['antacid','Antacid Drugs',6,'Pantoprazole 40mg, Sodium Bicarbonate 500mg, Rabeprazole and more',[['Pantoprazole Gastro Resistant Tablet IP','—','40 mg','Tablet'],['Sodium Bicarbonate Tablet','—','500 mg','Tablet'],['Rabeprazole Gastro Resistant Tablets IP','—','—','Tablet']]],
['mebendazole','Mebendazole Tablet',8,'Mebendazole 500 Mg, Vermox 100mg, Mebenda 100mg and more',[['Mebendazole Tablet','—','500 mg','Tablet'],['Vermox Mebendazole Tablets','Vermox','100 mg','Tablet'],['Mebenda Mebendazole Tablets','Mebenda','100 mg','Tablet']]],
['steroids','Steroids Tablets',5,'Oxandrol, Vidalista Black, Tadarise and more',[['Oxandrol Oxandrolone Tablets','Oxandrol','10 mg','Tablet'],['Vidalista Black Tadalafil Tablets','Vidalista Black','80 mg','Tablet'],['Tadarise Tadalafil Effervescent Tablets','Tadarise','20 mg','Tablet']]],
['pregabalin','Pregabalin Capsules & Tablets',3,'Pregagesic, Pregacare, Nervigesic',[['Pregagesic Pregabalin Capsules','Pregagesic','300 mg','Capsule'],['Pregacare Pregabalin Capsule','Pregacare','300 mg','Capsule'],['Nervigesic Pregabalin Capsules','Nervigesic','300 mg','Capsule']]],
['vaccines','Vaccines',8,'Varicella Chickenpox, Pneumococcal, Typhoid and more',[['Varicella Chickenpox Vaccine Injection','—','—','Injection'],['Pneumococcal Polysaccharide Conjugate Vaccine','—','—','Vaccine'],['Typhoid Polysaccharide Vaccine IP','—','—','Vaccine']]],
['anticoagulant','Anticoagulant and Antiplatelet Drugs',4,'Apixaban 2.5 Mg, Apixaban 5 Mg, Alteplase 50mg and more',[['Apixaban 2.5 Mg Tablet','—','2.5 mg','Tablet'],['Apixaban 5 Mg Tablet','—','5 mg','Tablet'],['Alteplase Injection','—','50 mg','Injection']]],
['anti-infective','Anti Infective Medicine',9,'Posaconazole 100mg, Voriconazole 200 Mg Injection, Micafungin 50mg Injection and more',[['Posaconazole 100mg Tablet','—','100 mg','Tablet'],['Voriconazole 200 Mg Injection','—','200 mg','Injection'],['Micafungin 50mg Injection','—','50 mg','Injection']]],
['antiparasitic','Antiparasitic Drug',9,'Alkem Metro I.V. 500 Mg, Dicarris Levamisole 50 Mg, Ketoconazole Soap 2% and more',[['Alkem Metro I.V.','Alkem','500 mg','IV'],['Dicarris Levamisole Hydrochloride Tablets','Dicarris','50 mg','Tablet'],['Ketoconazole Soap 2%','—','2%','Soap']]],
['metronidazole','Metronidazole Tablet',10,'Metropin 250mg, Metron 400mg, Metropin 500mg and more',[['Metropin Metronidazole Tablets','Metropin','250 mg','Tablet'],['Metron Metronidazole Tablets','Metron','400 mg','Tablet'],['Metropin Metronidazole Tablets','Metropin','500 mg','Tablet']]],
['cream','Pharmaceutical Cream',6,'Oricon Econazole Nitrate Cream, Fluconazole, Ketoconazole Dusting Powder and more',[['Oricon Econazole Nitrate Cream','Oricon','1%','Cream'],['Fluconazole Tablets IP','—','—','Tablet'],['Ketoconazole Dusting Powder','—','—','Powder']]],
['nitazoxanide','Nitazoxanide Tablets',6,'Nizonide DT 200 Mg, Nizonide 500Mg, NITASAFE 500 Mg and more',[['Nizonide DT Nitazoxanide Tablet','Nizonide','200 mg','Tablet'],['Nizonide Nitazoxanide Tablet','Nizonide','500 mg','Tablet'],['NITASAFE Nitazoxanide Tablet','NITASAFE','500 mg','Tablet']]],
['arthritis','Arthritic Drugs',3,'Aceclofenac + Paracetamol, Aceclofenac + Thiocolchicoside, Upadacitinib Rinvoq 15 Mg',[['Aceclofenac And Paracetamol Tablet IP','—','—','Tablet'],['Aceclofenac And Thiocolchicoside Tablets','—','—','Tablet'],['Upadacitinib Rinvoq 15 Mg Tablet','Rinvoq','15 mg','Tablet']]],
['paracetamol','Paracetamol Tablets',4,'Paracetamol 500 Mg, Paracip 650, Griseofulvin 500 Mg and more',[['Paracetamol Tablets','—','500 mg','Tablet'],['Paracip 650 Paracetamol Tablets','Paracip','650 mg','Tablet'],['Griseofulvin 500 Mg Tablets','—','500 mg','Tablet']]],
['multivitamin','Multivitamin Tablets & Capsules',4,'Revital, Supradyn, Zincovit and more',[['Revital Multivitamin Tablets','Revital','—','Tablet'],['Supradyn Multivitamin Tablet','Supradyn','—','Tablet'],['Zincovit Multivitamin Tablet','Zincovit','—','Tablet']]],
['methenolone','Methenolone Enanthate Injection',2,'Vitlira Vardenafil Tablets, Methenolone Enanthate Injection',[['Vitlira Vardenafil Tablets','Vitlira','40 mg','Tablet'],['Methenolone Enanthate Injection','—','100 mg/ml','Injection']]],
['albendazole','Albendazole Tablets',5,'Zolbend 400mg and Aldol 400mg products and more',[['Zolbend Albendazole Chewable Tablets','Zolbend','400 mg','Tablet'],['Aldol Albendazole Tablet','Aldol','400 mg','Tablet'],['Zolbend Albendazole Chewable Tablets','Zolbend','400 mg','Tablet']]],
['tetanus','Tetanus Vaccine',3,'Tetanus Toxoid, Quadrovax SD/PFS, Diphtheria Tetanus Pertussis Vaccine',[['Tetanus Toxoid Injection','—','—','Injection'],['Quadrovax SD/PFS Vaccine','Quadrovax','—','Vaccine'],['Diphtheria Tetanus Pertussis Vaccine','—','—','Vaccine']]],
['weight-loss','Weight Loss Medicine',2,'Orligal Orlistat Capsules, Naltrexone 50mg Tablets',[['Orligal Orlistat Capsules','Orligal','120 mg','Capsule'],['Naltrexone Tablets','—','50 mg','Tablet']]],
['triclabendazole','Triclabendazole Tablet',4,'Triclabend 250 Mg, Triclabend 500mg and more',[['Triclabend 250 Mg Triclabendazole Tablet','Triclabend','250 mg','Tablet'],['Triclabend Triclabendazole Tablets','Triclabend','500 mg','Tablet'],['Triclabend 250 Mg Triclabendazole Tablet','Triclabend','250 mg','Tablet']]],
['dark-chocolate','Dark Chocolate',1,'Herbal Dark Chocolate',[['Herbal Dark Chocolate','—','—','Food product']]],
['pyrantel','Pyrantel Pamoate',2,'Nemocid 250mg oral suspension and tablets',[['Nemocid Pyrantel Pamoate Oral Suspension','Nemocid','250 mg','Oral suspension'],['Nemocid Pyrantel Pamoate Tablets','Nemocid','250 mg','Tablet']]],
['other','Other Products',105,'Filagra, Ivermectin and other products in the wider catalogue',[['Filagra Sildenafil Oral Jelly','Filagra','100 mg','Oral jelly'],['Filagra Sildenafil Citrate Tablets','Filagra','100 mg','Tablet'],['Iverheal Ivermectin Tablets','Iverheal','12 mg','Tablet']]]
];
const FEATURED=[
['erectile','Erectile Dysfunction Medicine',9,'Selected products from the Etnova Pharma product range.',[['Sildalist Sildenafil Citrate and Tadalafil Tablets','Sildalist','60 mg','Tablet'],['20mg Tadarise Tadalafil Effervescent Tablets','Tadarise','20 mg','Tablet'],['5mg Vidalista Tadalafil Tablets','Vidalista','5 mg','Tablet'],['Tadalafil Tablets 20mg','Tadacip','20 mg','Tablet'],['250mg TestoBoon Testosterone Propionate Injection','TestoBoon','250 mg','Injection']]],
['tablets','Pharmaceutical Tablets',5,'Selected pharmaceutical tablet products from the current website catalogue.',[['50mg Enclomisign Enclomiphene Tablets','Enclomisign','50 mg','Tablet'],['50mg Enclomy Enclomiphene Tablets','Enclomy','50 mg','Tablet'],['25mg Enclomy Enclomiphene Tablets','Enclomy','25 mg','Tablet'],['350mg Prosoma Carisoprodol Tablet','Prosoma','350 mg','Tablet'],['1000mg Mebentel Mebendazole Tablets','Mebentel','1000 mg','Tablet']]],
['anti-cancer','Anti Cancer Medicines',0,'Products in this category will be populated from the verified Etnova Pharma catalogue before launch.',[]]
];
const ALLC=C.concat(FEATURED);
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const key=new URLSearchParams(location.search).get('category');const grid=document.getElementById('categoryGrid');const productView=document.getElementById('productView');const categoryView=document.getElementById('categoryView');
function cards(){grid.innerHTML=ALLC.map((c,i)=>`<a class="category-card" href="catalogue.html?category=${c[0]}"><span class="category-number">${String(i+1).padStart(2,'0')}</span><h3>${esc(c[1])}</h3><p>${esc(c[3])}</p><span class="category-meta">Total products: ${c[2]}</span><span class="category-link">Open Category →</span></a>`).join('')}
function setupCategoryToggle(){const b=document.getElementById('viewMoreCategories');if(!b)return;b.onclick=()=>{const open=grid.classList.toggle('is-expanded');b.textContent=open?'Show Fewer Categories':'View More Categories';b.setAttribute('aria-expanded',String(open));if(open)b.scrollIntoView({behavior:'smooth',block:'nearest'})}}
function openModal(p){document.getElementById('modalProduct').textContent=`${p[0]} · ${p[2]} · ${p[3]}`;document.getElementById('selectedProduct').value=p[0];document.getElementById('productModal').classList.add('open');document.getElementById('productModal').setAttribute('aria-hidden','false');document.getElementById('customerName').focus()}
function closeModal(){document.getElementById('productModal').classList.remove('open');document.getElementById('productModal').setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=closeModal);document.addEventListener('keydown',e=>e.key==='Escape'&&closeModal());
const cat=ALLC.find(x=>x[0]===key);if(!cat){cards();setupCategoryToggle()}else{categoryView.hidden=true;productView.hidden=false;document.getElementById('categoryTitle').textContent=cat[1];document.getElementById('categoryIntro').textContent=`${cat[2]} products are listed in this category. Showing only products assigned to ${cat[1]}.`;document.getElementById('selectedCategoryTitle').textContent=cat[1];document.getElementById('selectedCategoryMeta').textContent=`Total products shown in catalogue record: ${cat[2]}`;const search=document.getElementById('categoryProductSearch');function render(){const q=search.value.toLowerCase().trim();const list=cat[4].filter(p=>p.join(' ').toLowerCase().includes(q));document.getElementById('categoryProductGrid').innerHTML=list.map((p,i)=>`<article class="product-card catalog-product product-card-clickable" tabindex="0"><div class="product-body"><span class="pill">${esc(p[1])}</span><h3>${esc(p[0])}</h3><dl><div><dt>Strength</dt><dd>${esc(p[2])}</dd></div><div><dt>Form</dt><dd>${esc(p[3])}</dd></div></dl><button class="btn btn-small" type="button">Request Availability</button></div></article>`).join('');document.getElementById('categoryNoResults').hidden=!!list.length;document.querySelectorAll('#categoryProductGrid .product-card').forEach((el,i)=>{el.onclick=()=>openModal(list[i]);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openModal(list[i])}}})}search.oninput=render;render()}
document.getElementById('productEnquiryForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const product=document.getElementById('selectedProduct').value;const body=`Hello Etnova Pharma,\n\nI would like to request availability for:\n${product}\n\nFull Name: ${document.getElementById('customerName').value}\nCompany: ${document.getElementById('companyName').value}\nEmail: ${document.getElementById('customerEmail').value}\nPhone / WhatsApp: ${document.getElementById('customerPhone').value}\nDestination Country: ${document.getElementById('destinationCountry').value}\nRequired Quantity: ${document.getElementById('requiredQuantity').value}\nMessage: ${document.getElementById('customerMessage').value}\n\nPlease confirm current availability, pricing, packaging and export requirements.`;const data=new FormData(f);data.set('_subject','Product Availability Request - '+product);data.set('_captcha','false');data.set('_template','table');data.set('WhatsApp message',body);const btn=f.querySelector('button[type=submit]');const old=btn.textContent;btn.disabled=true;btn.textContent='Sending…';try{const r=await fetch('https://formsubmit.co/ajax/etnovapharma@gmail.com',{method:'POST',headers:{'Accept':'application/json'},body:data});if(!r.ok)throw new Error();alert('Your product enquiry has been sent to Etnova Pharma.');window.open(`https://wa.me/918983128824?text=${encodeURIComponent(body)}`,'_blank','noopener');f.reset();document.getElementById('productModal').classList.remove('open')}catch(err){alert('We could not send the enquiry email right now. Please try again or use WhatsApp.')}finally{btn.disabled=false;btn.textContent=old;}};document.getElementById('year').textContent=new Date().getFullYear();